version: '3.2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/
      - ./docker/nginx:/etc/nginx/conf.d
      - ./var/log:/var/log/nginx/
    links:
      - php
  php:
    build: ./docker/php
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d # Place init .sql OR .sql.gz files here.
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
